this will now allow keyword tables like order
tshemsedinov/node-mysql-utilities pull request #20
Opened 2018-06-15 19:21 UTC by burtontanner

2018-06-16 23:48 UTC, tshemsedinov reviewed
Maybe it is better to add ` in escapeIdentifier

2018-06-18 10:30 UTC, tshemsedinov commented on utilities.js
> +        escapeIdentifier(table) +'`', [],
use `npm test` to see linter errors

2018-06-18 18:51 UTC, burtontanner commented
I just pushed some changes to move it into escapedIdentifier and npm test is working again.

2018-06-18 20:12 UTC, tshemsedinov requested changes

2018-06-18 20:12 UTC, tshemsedinov commented on utilities.js
> +  if (str === 'order') {
Why only order?

2018-06-18 20:12 UTC, tshemsedinov commented on utilities.js
> +  if (str === 'order') {
```
if (!reservedWords.includes(str) && identifierRegexp.test(str)) return str;
return '`' + str + '`';
```

2025-12-11 20:11 UTC, closed without merging